name: Android apk

on: push
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Flutter Runner
      uses: jddeep/Flutter-Runner@1.2.0
      
    - name: install dependencies
      uses: ./action
      with:
        args: pub get
        
    - name: clean stale build and cache
      uses: ./action
      with:
        args: clean

    - name: build apk
      uses: ./action
      with:
        args: build apk --release
